In [ ]:
import pandas as pd
from pathlib import Path

# 1. Xác định thư mục data
ROOT = Path.cwd()
DATA_DIR = ROOT/ ".." / "data" / "raw"

# 2. Đọc dữ liệu JSON
JSON_PATH = DATA_DIR / "du_lieu_adzuna_tho.json"

df = pd.read_json(JSON_PATH)

# 3. Chuyển JSON sang CSV
CSV_PATH = DATA_DIR / "du_lieu_adzuna_tho.csv"

df.to_csv(
    CSV_PATH,
    index=False,
    encoding="utf-8-sig"
)

In [12]:
df = pd.read_csv(CSV_PATH)

df.head()

,id,contract_type,redirect_url,salary_max,contract_time,latitude,created,category,longitude,title,location,description,salary_min,adref,salary_is_predicted,company,__CLASS__
0,5904487469,permanent,https://www.adzuna.com/land/ad/5904487469?se=3...,312845.06,full_time,37.393080,2026-09-30T22:39:48Z,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...",-122.077020,Principal Software Engineer,"{'area': ['US', 'California', 'Santa Clara Cou...",Microsoft and OpenAI have formed one of the mo...,312845.06,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiM09WQkNkdko4UkdIV...,1,"{'display_name': 'Microsoft', '__CLASS__': 'Ad...",Adzuna::API::Response::Job
1,5903572359,permanent,https://www.adzuna.com/details/5903572359?utm_...,99000.00,full_time,33.751486,2026-09-30T02:32:52Z,"{'tag': 'engineering-jobs', 'label': 'Engineer...",-117.754930,Software Engineer,{'__CLASS__': 'Adzuna::API::Response::Location...,ETAP empowers customers to make informed decis...,59500.00,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiM09WQkNkdko4UkdIV...,0,{'__CLASS__': 'Adzuna::API::Response::Company'...,Adzuna::API::Response::Job
2,5879639363,permanent,https://www.adzuna.com/details/5879639363?utm_...,106080.02,full_time,37.798085,2026-09-11T07:15:48Z,"{'label': 'IT Jobs', 'tag': 'it-jobs', '__CLAS...",-122.466538,Software Engineer,{'__CLASS__': 'Adzuna::API::Response::Location...,"Responsibilities Design, implement, and mainta...",106080.02,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiM09WQkNkdko4UkdIV...,1,{'__CLASS__': 'Adzuna::API::Response::Company'...,Adzuna::API::Response::Job
3,5887617106,permanent,https://www.adzuna.com/details/5887617106?utm_...,227000.00,full_time,38.664532,2026-09-17T07:29:42Z,"{'label': 'IT Jobs', 'tag': 'it-jobs', '__CLAS...",-121.145000,Software Engineer,{'__CLASS__': 'Adzuna::API::Response::Location...,"Voyager is an innovative space, defense, and n...",104000.00,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg4NzYxNzEwNiIsI...,0,{'__CLASS__': 'Adzuna::API::Response::Company'...,Adzuna::API::Response::Job
4,5885956386,permanent,https://www.adzuna.com/details/5885956386?utm_...,121100.00,full_time,34.508431,2026-09-16T06:30:22Z,"{'label': 'Engineering Jobs', 'tag': 'engineer...",-119.731021,Software Engineer,"{'display_name': 'Goleta, Santa Barbara County...",Be visionary Teledyne Technologies Incorporate...,90800.00,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiM09WQkNkdko4UkdIV...,0,"{'display_name': 'Teledyne Technologies', '__C...",Adzuna::API::Response::Job

In [6]:
df.shape

(2403, 17)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2403 entries, 0 to 2402
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2403 non-null   int64
 1   contract_type        2403 non-null   str
 2   redirect_url         2403 non-null   str
 3   salary_max           2403 non-null   float64
 4   contract_time        2403 non-null   str
 5   latitude             2131 non-null   float64
 6   created              2403 non-null   str
 7   category             2403 non-null   str
 8   longitude            2131 non-null   float64
 9   title                2403 non-null   str
 10  location             2403 non-null   str
 11  description          2403 non-null   str
 12  salary_min           2403 non-null   float64
 13  adref                2403 non-null   str
 14  salary_is_predicted  2403 non-null   int64
 15  company              2403 non-null   str
 16  __CLASS__            2403 non-null   str
dtypes: float64(4), int64(2), str(11)
memory usage: 319.3 KB

In [16]:
df.describe()

,id,salary_max,latitude,longitude,salary_min,salary_is_predicted
count,2.403000e+03,2403.000000,2131.000000,2131.000000,2403.000000,2403.000000
mean,5.872564e+09,184644.097782,34.879758,-97.474852,156239.376184,0.523512
std,1.201117e+08,76880.800208,4.233099,18.578879,72618.293331,0.499551
min,4.804438e+09,1.000000,18.362063,-122.466538,0.000000,0.000000
25%,5.871842e+09,130645.365000,32.502900,-118.352039,109754.320000,0.000000
50%,5.912528e+09,177700.000000,33.912781,-96.767002,143860.770000,1.000000
75%,5.926441e+09,234000.000000,38.884513,-77.093858,188744.555000,1.000000
max,5.931582e+09,600000.000000,40.846188,-66.567142,535280.440000,1.000000

In [14]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
})

print(missing)

                     missing_count  missing_percent
id                               0         0.000000
contract_type                    0         0.000000
redirect_url                     0         0.000000
salary_max                       0         0.000000
contract_time                    0         0.000000
latitude                       272        11.319184
created                          0         0.000000
category                         0         0.000000
longitude                      272        11.319184
title                            0         0.000000
location                         0         0.000000
description                      0         0.000000
salary_min                       0         0.000000
adref                            0         0.000000
salary_is_predicted              0         0.000000
company                          0         0.000000
__CLASS__                        0         0.000000

In [15]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df["id"].duplicated().sum())
print("Duplicate adrefs:", df["adref"].duplicated().sum())

Duplicate rows: 0
Duplicate IDs: 446
Duplicate adrefs: 0